name: Build Executable for Windows 7

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --collect-all serial gemini-code-1786699564323.py

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: CNC-Manager-Win7
        path: dist/*.exe
